name: CaptureTheFlag
version: '${project.version}'
main: br.com.thomaszoord.CaptureTheFlag
author: thomaszoord
softdepend: [SCVerso]
commands:
  ctf:
    description: 'Comando principal do plugin. Use /ctf help para mais detalhes'
  time:
  kit:
  g: